CREATE TABLE IF NOT EXISTS tb_journal_entries (
    journal_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    accounting_date date NULL,
    currency_code varchar(255) NULL,
    journal_name varchar(255) NULL,
    CONSTRAINT tb_journal_entries_pkey PRIMARY KEY (journal_id)
);