CREATE TABLE IF NOT EXISTS tb_journal_lines (
    line_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    account_code varchar(255) NULL,
    cost_center varchar(255) NULL,
    credit float8 NULL,
    debit float8 NULL,
    description varchar(255) NULL,
    journal_id int8 NULL,
    CONSTRAINT tb_journal_lines_pkey PRIMARY KEY (line_id)
 );
