services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: oracledb
    ports:
      - "5432:5432"
  rabbitmq:
      image: rabbitmq:management
      ports:
        - 15672:15672
        - 5672:5672
