spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oracledb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
queue:
  name:
    success: response-queue-success
    error: response-queue-error
jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub