spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oracledb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
queue:
  name: response-queue-submit
